id: P000355
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG09688
  title: ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་ཐར་བཀའ་གདམས་ཕ་ཆོས་
  author: ''
  volumes:
    359aa3676de941878233edcdf21fda73:
      image_group_id: I00KG09718
      title: Volume 1 of jo bo rje dpal ldan a ti sha'i rnam thar bka' gdams pha chos
      volume_number: 1
      total_pages: 910
      base_file: v001.txt
